Traceback (most recent call last):
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mol/micromamba/envs/moenv/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Superposition
hhl.h(q[1])
hhl.h(q[2])
# Controlled-U0
hhl.cu3(-Ï€ / 2, -Ï€ / 2, Ï€ / 2, q[2], q[3])
hhl.cu1(3 * Ï€ / 4, q[2], q[3])
hhl.cx(q[2], q[3])
hhl.cu1(3 * Ï€ / 4, q[2], q[3])
hhl.cx(q[2], q[3])
# Controlled-U1
hhl.cx(q[1], q[3])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      3[0m hhl[38;5;241m.[39mh(q[[38;5;241m2[39m])
[1;32m      4[0m [38;5;66;03m# Controlled-U0[39;00m
[0;32m----> 5[0m [43mhhl[49m[38;5;241;43m.[39;49m[43mcu3[49m([38;5;241m-[39mÏ€ [38;5;241m/[39m [38;5;241m2[39m, [38;5;241m-[39mÏ€ [38;5;241m/[39m [38;5;241m2[39m, Ï€ [38;5;241m/[39m [38;5;241m2[39m, q[[38;5;241m2[39m], q[[38;5;241m3[39m])
[1;32m      6[0m hhl[38;5;241m.[39mcu1([38;5;241m3[39m [38;5;241m*[39m Ï€ [38;5;241m/[39m [38;5;241m4[39m, q[[38;5;241m2[39m], q[[38;5;241m3[39m])
[1;32m      7[0m hhl[38;5;241m.[39mcx(q[[38;5;241m2[39m], q[[38;5;241m3[39m])

[0;31mAttributeError[0m: 'QuantumCircuit' object has no attribute 'cu3'
AttributeError: 'QuantumCircuit' object has no attribute 'cu3'

